artifact_uri: file:///home/mle-user/mle_projects/mle-mlflow/mlflow_experiments_store/0/38ddb5a606234ca2b39e43cf93562640/artifacts
end_time: 1721553423601
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 38ddb5a606234ca2b39e43cf93562640
run_name: Default
run_uuid: 38ddb5a606234ca2b39e43cf93562640
source_name: ''
source_type: 4
source_version: ''
start_time: 1721553423594
status: 3
tags: []
user_id: mle-user
